// todo-api/assets/components/TodoNote.vue
<template>
  <div>
    <b-card v-if="!editing" class="my-1">
      <b-row>
        <b-col>
          <b-form-checkbox
            v-model="task.completed"
            @change="fireUpdate(task)"
            name="check-button"
            switch
          >
            <h5 class="card-title px-1">{{ task.title }}</h5>
          </b-form-checkbox>
        </b-col>
        <b-col class="text-end"
          ><i
            class="bi bi-pencil-square clickable mx-1"
            @click="editing = !editing"
          ></i>
          <i class="bi bi-trash clickable mx-1" @click="fireDelete(task)"></i>
        </b-col>
      </b-row>

      <b-card-text> {{ task.description }} </b-card-text>
      <b-badge variant="primary">{{ task.category.name }}</b-badge>
    </b-card>
    <b-card v-else>
      <b-form-group
        class="mb-3"
        id="task-title"
        label="Name:"
        label-for="title"
        description="The title of the task."
      >
        <b-form-input
          id="title"
          v-model="task.title"
          type="text"
          :disabled="loading"
          placeholder="Your task..."
          required
        ></b-form-input>
      </b-form-group>
      <b-form-group
        class="mb-3"
        id="task-desc"
        label="Description:"
        label-for="desc"
        description="The Description of the task."
      >
        <b-form-input
          id="desc"
          v-model="task.description"
          type="text"
          :disabled="loading"
          placeholder="What would you like to do?"
          required
        ></b-form-input>
      </b-form-group>
      <div class="mb-3">
        <b-form-select
          v-model="task.category.id"
          :options="categoryOptions"
        ></b-form-select>
      </div>
      <b-button
        @click="fireUpdate(task)"
        :disabled="loading"
        variant="primary"
        size="sm"
      >
        Save
      </b-button>
      <b-button
        @click="editing = !editing"
        :disabled="loading"
        size="sm"
        variant="outline-secondary"
        class="mx-2"
      >
        Cancel
      </b-button>
    </b-card>
  </div>
</template>

<script>
export default {
  props: {
    loading: {
      type: Boolean,
      default: false,
    },
    categories: {
      type: Array,
      default: () => [],
    },
    task: {
      type: Object,
      default: () => ({}),
    },
  },
  computed: {
    categoryOptions() {
      return this.categories.map((c) => ({
        value: c.id,
        text: c.name,
      }));
    },
  },
  data() {
    return {
      editing: false,
    };
  },
  methods: {
    fireDelete(task) {
      this.$emit("delete", task);
    },
    fireUpdate(task) {
      this.$emit("update", task);
      this.editing = false;
    },
  },
};
</script>

<style></style>

// todo-frontend/src/app/components/todo-note/todo-note.component.ts
import {
  Component,
  EventEmitter,
  Input,
  OnChanges,
  OnInit,
  Output,
  SimpleChanges,
} from '@angular/core';
import { Category } from 'src/app/model/Category';
import { TaskStatus, TodoTask } from 'src/app/model/TodoTask';

@Component({
  selector: 'app-todo-note',
  templateUrl: './todo-note.component.html',
  styleUrls: ['./todo-note.component.scss'],
})
export class TodoNoteComponent implements OnInit {
  TaskStatus = TaskStatus;
  private _editing = false;

  @Input()
  loading = false;

  @Input()
  task: TodoTask = {} as TodoTask;

  @Input()
  get editing() {
    return this._editing;
  }

  @Output()
  editingChange = new EventEmitter<boolean>();

  set editing(val) {
    this._editing = val;
    this.editingChange.emit(this._editing);
  }

  @Input()
  categoryTitle = '';

  @Input()
  categories: Category[] = [];

  @Output()
  delete: EventEmitter<TodoTask> = new EventEmitter<TodoTask>();

  @Output()
  changeStatus: EventEmitter<{ task: TodoTask; status: TaskStatus }> =
    new EventEmitter();

  @Output()
  update: EventEmitter<TodoTask> = new EventEmitter();

  constructor() {}

  ngOnInit(): void {}

  fireChangeStatus(task: TodoTask, $event: any) {
    this.changeStatus.emit({
      task,
      status: $event.srcElement.checked
        ? TaskStatus.Done
        : TaskStatus.InProgress,
    });
  }

  fireDelete(task: TodoTask) {
    this.delete.emit(task);
  }

  fireUpdate(task: TodoTask) {
    this.update.emit(task);
  }
}

<div class="card-body" *ngIf="!editing">
  <div class="row">
    <div class="col">
      <div class="form-check form-switch">

        <input class="form-check-input" (change)="fireChangeStatus(task,$event)"
          [checked]="task.status === TaskStatus.Done" type="checkbox" role="switch" id="doneCheck">
        <label for="doneCheck" class="form-check-label">
          <h5 class="card-title">{{task.title}}</h5>
        </label>

      </div>
    </div>
    <div class="col text-end">
      <i class="bi bi-pencil-square clickable mx-1" (click)="editing = !editing"></i>
      <i class="bi bi-trash clickable mx-1" (click)="fireDelete(task)"></i>
    </div>
  </div>
  <p class="card-text">{{task.description}}</p>
  <span class="badge bg-success">{{categoryTitle}}</span>
</div>
<div class="card-body" *ngIf="editing">
  <div class="mb-3">
    <label for="title" class="form-label ">Title</label>
    <input type="text" [(ngModel)]="task.title" class="form-control form-control-sm" id="title"
      aria-describedby="title-help" [disabled]="loading">
    <div id="title-help" class="form-text">The title of the task</div>
  </div>
  <div class="mb-3">
    <label for="description" class="form-label">Description</label>
    <input type="text" [(ngModel)]="task.description" class="form-control form-control-sm" id="description"
      aria-describedby="description-help" [disabled]="loading">
    <div id="description-help" class="form-text">A short description of the task</div>
  </div>
  <div class="mb-3">
    <select class="form-select form-select-sm" aria-label="category" [(ngModel)]="task.categoryId" [disabled]="loading">
      <option [ngValue]="category.id" *ngFor="let category of categories">{{category.title}}
      </option>
    </select>
  </div>
  <button type="button" (click)="fireUpdate(task)" [disabled]="loading" class="btn btn-primary btn-sm">Save</button>
  <button type="button" (click)="editing = !editing" [disabled]="loading" class="btn btn-outline-secondary mx-2 btn-sm">Cancel</button>
</div>
