// todo-frontend/src/app/components/category/category.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Category } from 'src/app/model/Category';

@Component({
  selector: 'app-category',
  templateUrl: './category.component.html',
  styleUrls: ['./category.component.scss'],
})
export class CategoryComponent implements OnInit {
  private _editing = false;
  constructor() {}

  @Input()
  category: Category = {} as Category;

  @Input()
  get editing() {
    return this._editing;
  }

  @Output()
  editingChange = new EventEmitter<boolean>();
  set editing(val) {
    this._editing = val;
    this.editingChange.emit(this._editing);
  }

  @Output()
  delete: EventEmitter<Category> = new EventEmitter<Category>();

  @Output()
  update: EventEmitter<Category> = new EventEmitter();

  ngOnInit(): void {}

  fireDelete(task: Category) {
    this.delete.emit(task);
  }

  fireUpdate(task: Category) {
    this.update.emit(task);
  }
}

<div class="card-body" *ngIf="!editing">
  <div class="row">
    <div class="col">
      <h5 class="card-title">{{category.title}}</h5>
    </div>
    <div class="col text-end">
      <i class="bi bi-pencil-square clickable mx-1" (click)="editing = !editing"></i>
      <i *ngIf="category.id!==1" class="bi bi-trash clickable mx-1" (click)="fireDelete(category)"></i>
    </div>
  </div>
  <p class="card-text">{{category.description}}</p>
</div>
<div class="card-body" *ngIf="editing">
  <div class="mb-3">
    <label for="title" class="form-label ">Title</label>
    <input type="text" [(ngModel)]="category.title" class="form-control form-control-sm" id="title"
      aria-describedby="title-help">
    <div id="title-help" class="form-text">The title of the category</div>
  </div>
  <div class="mb-3">
    <label for="description" class="form-label">Description</label>
    <input type="text" [(ngModel)]="category.description" class="form-control form-control-sm" id="description"
      aria-describedby="description-help">
    <div id="description-help" class="form-text">A short description of the category</div>
  </div>
  <button type="button" (click)="fireUpdate(category)" class="btn btn-primary btn-sm">Save</button>
  <button type="button" (click)="editing = !editing" class="btn btn-outline-secondary mx-2 btn-sm">Cancel</button>
</div>

// todo-api/assets/components/Category.vue
<template>
  <div>
    <b-card v-if="!editing" class="my-1">
      <b-row>
        <b-col>
          <h5 class="card-title">{{ category.name }}</h5>
        </b-col>
        <b-col class="text-end"
          ><i
            class="bi bi-pencil-square clickable mx-1"
            @click="editing = !editing"
          ></i>
          <i
            class="bi bi-trash clickable mx-1"
            @click="fireDelete(category)"
          ></i>
        </b-col>
      </b-row>

      <b-card-text> {{ category.description }} </b-card-text>
    </b-card>
    <b-card v-else>
      <b-form-group
        class="mb-3"
        id="category-title"
        label="Name:"
        label-for="title"
        description="The title of the category."
      >
        <b-form-input
          id="title"
          v-model="category.name"
          type="text"
          placeholder="Category"
          required
        ></b-form-input>
      </b-form-group>
      <b-form-group
        class="mb-3"
        id="category-description"
        label="Description:"
        label-for="desc"
        description="The title of the category."
      >
        <b-form-input
          id="desc"
          v-model="category.description"
          type="text"
          placeholder="Description"
          required
        ></b-form-input>
      </b-form-group>

      <b-button
        @click="fireUpdate(category)"
        :disabled="loading"
        variant="primary"
        size="sm"
      >
        Save
      </b-button>
      <b-button
        @click="editing = !editing"
        :disabled="loading"
        size="sm"
        variant="outline-secondary"
        class="mx-2"
      >
        Cancel
      </b-button>
    </b-card>
  </div>
</template>

<script>
export default {
  name: "Category",
  props: {
    loading: {
      type: Boolean,
      default: false,
    },
    category: {
      type: Object,
      default: () => ({}),
    },
  },
  data() {
    return {
      editing: false,
    };
  },
  methods: {
    fireDelete(category) {
      this.$emit("delete", category);
    },
    fireUpdate(category) {
      this.$emit("update", category);
      this.editing = false;
    },
  },
};
</script>

<style></style>
