// todo-api/assets/components/CategoryList.vue
<template>
  <div v-if="firstLoading">
    <b-spinner label=""></b-spinner>
  </div>
  <div v-else>
    <div v-if="errorDescripiton">
      <b-alert variant="danger" show>
        <strong>An error occured:</strong> {{ errorDescripiton }}
        <div class="mt-3">
          <b-button variant="primary" @click="loadData()"
            >Try again...</b-button
          >
        </div>
      </b-alert>
    </div>
    <div v-else>
      <category
        v-for="category in categories"
        :key="category.id"
        :category="category"
        @update="updateCategory"
        @delete="deleteCategory"
      ></category>
      <b-card class="mb-3" v-if="isAdding">
        <b-card-body>
          <b-form-group
            class="mb-3"
            id="category-title"
            label="Name:"
            label-for="title"
            description="The title of the category."
          >
            <b-form-input
              id="title"
              v-model="newCategory.name"
              type="text"
              placeholder="Category"
              required
            ></b-form-input>
          </b-form-group>
          <b-form-group
            class="mb-3"
            id="category-description"
            label="Description:"
            label-for="desc"
            description="The title of the category."
          >
            <b-form-input
              id="desc"
              v-model="newCategory.description"
              type="text"
              placeholder="Description"
              required
            ></b-form-input>
          </b-form-group>
          <b-button @click="saveNew()" variant="primary" size="sm"
            >Save</b-button
          >
          <b-button @click="cancelNew()" variant="outline-secondary" size="sm"
            >Cancel</b-button
          >
        </b-card-body>
      </b-card>
      <b-card v-else>
        <b-button @click="toggleAddingMode(true)" variant="primary" size="sm">
          Add..
        </b-button>
      </b-card>
    </div>
  </div>
</template>
<script>
import CategoryClient from "../mixins/CategoryClient";
import Category from "./Category.vue";

export default {
  name: "CategoryList",
  props: {},
  components: { Category },
  mixins: [CategoryClient],
  computed: {},
  data() {
    return {
      loading: false,
      categories: [],
      isAdding: false,
      firstLoading: false,
      showDone: true,
      errorDescripiton: undefined,
      newCategory: {},
    };
  },
  methods: {
    loadData() {
      this.loading = true;
      this.categoryApiClient
        .list()
        .exec()
        .then((cats) => {
          this.categories = cats;
          this.loading = false;
          this.firstLoading = false;
          this.isEditing = {};
          for (const c of cats) {
            this.isEditing[c.id] = false;
          }
        });
    },

    updateCategory(category) {
      this.loading = true;
      category.owner = `/api/users/1`;
      this.categoryApiClient
        .update(category.id, category)
        .then(() => {
          this.loadData();
        })
        .catch((e) => {
          this.loadData();
        });
    },
    deleteCategory(category) {
      this.categories = this.categories.filter((t) => t.id !== category.id);
      this.loading = true;
      this.categoryApiClient
        .remove(category.id)
        .then(() => {
          this.loadData();
        })
        .catch((e) => {
          this.errorDescription = e.message;
        });
    },
    saveNew() {
      this.isAdding = false;
      this.newCategory.owner = `/api/users/1`;
      this.categories.push(this.newCategory);
      this.categoryApiClient
        .add(this.newCategory)
        .then(() => {
          this.loadData();
        })
        .catch((e) => {
          this.errorDescripiton = e.message;
        })
        .finally(() => {
          this.newCategory = {};
        });
    },
    cancelNew() {
      this.isAdding = false;
      this.newTask = {};
    },
    toggleAddingMode(enabled) {
      this.isAdding = enabled;
    },
  },
  mounted() {
    this.firstLoading = true;
    this.loadData();
  },
};
</script>

// todo-frontend/src/app/components/category-list/category-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Category } from 'src/app/model/Category';
import { AbstractCategoryStore } from 'src/app/services/AbstractCategoryStore.service';

@Component({
  selector: 'app-category-list',
  templateUrl: './category-list.component.html',
  styleUrls: ['./category-list.component.scss'],
})
export class CategoryListComponent implements OnInit {
  categories: Category[] = [];
  loading = false;
  firstLoading = true;
  isAdding = false;
  showDone = true;
  newCategory: Category = {} as Category;
  isEditing: Record<number, boolean> = {};
  errorDescription: string | undefined = undefined;
  constructor(protected categoryStore: AbstractCategoryStore) {}

  ngOnInit(): void {
    this.loadData();
  }

  loadData(): void {
    this.loading = true;
    this.errorDescription = undefined;
    this.categoryStore.getAll().subscribe({
      next: (cats) => {
        this.firstLoading = false;
        this.categories = cats;
      },
      error: (e: Error) => {
        this.firstLoading = false;
        this.errorDescription = e.message;
      },
    });
  }

  toggleEditMode(taskId: number, enabled: boolean) {
    this.isEditing[taskId] = enabled;
  }

  updateCategory(category: Category) {
    this.loading = true;
    this.categoryStore.update(category).subscribe({
      next: () => {
        this.toggleEditMode(category.id, false);
        this.loadData();
      },
      error: (e: Error) => {
        this.errorDescription = e.message;
      },
    });
  }

  deleteCategory(category: Category) {
    this.categories = this.categories.filter((c) => c.id !== category.id);
    this.loading = true;
    this.categoryStore.remove(category.id).subscribe({
      next: () => {
        this.loadData();
        this.loading = false;
      },
      error: (e: Error) => {
        this.errorDescription = e.message;
        this.loading = false;
      },
    });
  }

  toggleAddingMode(enabled: boolean) {
    this.isAdding = enabled;
  }

  saveNew() {
    this.isAdding = false;
    this.categories.push(this.newCategory);
    this.categoryStore.add(this.newCategory).subscribe({
      next: () => {
        this.cancelNew();
        this.loadData();
      },
      error: (e: Error) => {
        this.errorDescription = e.message;
      },
    });
  }

  cancelNew() {
    this.isAdding = false;
    this.newCategory = {} as Category;
  }
}

<div *ngIf="firstLoading">
  <div class="spinner-border" role="status">
    <!-- <span class="sr-only">Loading...</span> -->
  </div>
</div>
<div *ngIf="!firstLoading">
  <div *ngIf="errorDescription">
    <div class="alert alert-danger" role="alert">
      <strong>An error occured:</strong>{{errorDescription}}
      <div class="mt-3">
        <button (click)="loadData()" class="btn btn-primary btn-sm">Try again</button>
      </div>
    </div>
  </div>
  <div *ngIf="!errorDescription">
    <div class="row">
      <div class="card mb-3" *ngFor="let cat of categories">
        <app-category [category]="cat" [(editing)]="isEditing[cat.id]" (update)="updateCategory(cat)"
          (delete)="deleteCategory(cat)" (update)="updateCategory(cat)"></app-category>
      </div>
      <div class="card mb-3" *ngIf="!isAdding">
        <div class="card-body">
          <button type="button" (click)="toggleAddingMode(true)" class="btn btn-primary btn-sm">Add...</button>
        </div>
      </div>
      <div class="card mb-3" *ngIf="isAdding">
        <div class="card-body">

          <div class="mb-3">
            <label for="title" class="form-label ">Title</label>
            <input type="text" [(ngModel)]="newCategory.title" class="form-control form-control-sm" id="title"
              aria-describedby="title-help">
            <div id="title-help" class="form-text">The title of the category</div>
          </div>
          <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <input type="text" [(ngModel)]="newCategory.description" class="form-control form-control-sm"
              id="description" aria-describedby="description-help">
            <div id="description-help" class="form-text">A short description of the category</div>
          </div>
          <button type="button" (click)="saveNew()" class="btn btn-primary btn-sm">Save</button>
          <button type="button" (click)="cancelNew()" class="btn btn-outline-secondary mx-2 btn-sm">Cancel</button>
        </div>
      </div>
    </div>
  </div>
</div>
